---
language: ruby
before_install:
  - rm Gemfile.lock || true
  - gem update --system 2.1.11
  - gem --version
rvm:
  - 1.8.7
  - 1.9.3
script: bundle exec rake test
env:
  matrix:
  - PUPPET_VERSION="~> 2.7.0"
  - PUPPET_VERSION="~> 3.1.0"
  - PUPPET_VERSION="~> 3.4.0"
